### ISSUE TITLE
Improve from*Sigil functions

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-uri2#18]
E.g. fromMessageSigil

1. Make them idempotent (i.e. if you input a message URI into fromMessageSigil it should spit out the same URI). This would allow you to safely map an array of combined sigils and uris into an array of just uris.
2. Add format checking. Inputting a feedId (sigil or uri) into fromMessageSigil should error

**Comment by staltz** [comment]
Yes to `2` but I'm not sure about `1`. It's part of the API contract that you provide correct inputs, if the input isn't a message sigil than that's more like an error case. In the array map, you can just check what the value is, before passing it to ssb-uri2

**Comment by Powersource** [comment]
> you can just check what the value is

Yes but then I need to import and juggle ssb-ref too and have a bunch of ternary conditions. Maybe add an extra function that's specifically idempotent?

Hmm instead of checking if it's a sigil maybe I can do the opposite and check if it's a uri. And that combined with 2. allows me to not import ssb-ref directly.

**Comment by staltz** [comment]
Yeah you could do that instead. I don't like adding extra sugar to low-level libraries when there's another way of building the sugar. E.g. just make a function `fn` that juggles these if and elses, and do `array.map(fn)`

**Comment by Powersource** [comment]
Yeah maybe that's premature optimization
